### ISSUE TITLE
Infografía Realidad Aumentada

### ISSUE THREAD

**Issue by CarlosSD16** [SistemasTecTlaxiaco/infografia-CarlosSD16#1]
[Infografia_JuanCarlosChavezSantiago.pdf](https://github.com/SistemasTecTlaxiaco/infografia-CarlosSD16/files/8127276/Infografia_JuanCarlosChavezSantiago.pdf)

**Comment by Christopherg2** [comment]
Muy bien compañero tu trabajo esta completo, y cumple con todos los requisitos. 
20 puntos

**Comment by josealfredo79** [comment]
Muy bien hecho y revisado
