### ISSUE TITLE
infografia Juan Carlos Chavez Santiago

### ISSUE THREAD

**Issue by CarlosSD16** [SistemasTecTlaxiaco/infografia-CarlosSD16#2]
[infografia.pdf](https://github.com/SistemasTecTlaxiaco/infografia-CarlosSD16/files/6093996/infografia.pdf)

**Comment by Joel343** [comment]
**calificacion= 19**
1.- Colores menos flourecetes.
2.- Reducir un poco en cuanto a los textos.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
